-- --------------------------------------------------------
-- 호스트:                          127.0.0.1
-- 서버 버전:                        5.7.22-log - MySQL Community Server (GPL)
-- 서버 OS:                        Win64
-- HeidiSQL 버전:                  10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- gdkm 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `gdkm`;
CREATE DATABASE IF NOT EXISTS `gdkm` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `gdkm`;

-- 테이블 gdkm.T_ACHIVE_FEATURES_XREF 구조 내보내기
DROP TABLE IF EXISTS `T_ACHIVE_FEATURES_XREF`;
CREATE TABLE IF NOT EXISTS `T_ACHIVE_FEATURES_XREF` (
  `AFXREF_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACHIVE_ID` int(11) DEFAULT NULL,
  `FEATURES_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`AFXREF_ID`),
  KEY `ft_FEATURES_idx` (`FEATURES_ID`),
  KEY `ft_ACHIVE_idx` (`ACHIVE_ID`),
  CONSTRAINT `fk_T_ACHIVE_FEATURES_XREF_T_NGS_ACHIVE1` FOREIGN KEY (`ACHIVE_ID`) REFERENCES `T_NGS_DATA_ACHIVE` (`ACHIVE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_ACHIVE_FEATURES_XREF_T_NGS_DATA_FEATURES1` FOREIGN KEY (`FEATURES_ID`) REFERENCES `T_NGS_DATA_FEATURES` (`FEATURES_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=294019 DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_ACHIVE_HEADER_XREF 구조 내보내기
DROP TABLE IF EXISTS `T_ACHIVE_HEADER_XREF`;
CREATE TABLE IF NOT EXISTS `T_ACHIVE_HEADER_XREF` (
  `AHXREF_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACHIVE_ID` int(11) DEFAULT NULL,
  `HEADER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`AHXREF_ID`),
  KEY `ft_HEADER_idx` (`HEADER_ID`),
  KEY `ft_ACHIVE_idx` (`ACHIVE_ID`),
  CONSTRAINT `fk_T_ACHIVE_HEADER_XREF_T_NGS_DATA_ACHIVE1` FOREIGN KEY (`ACHIVE_ID`) REFERENCES `T_NGS_DATA_ACHIVE` (`ACHIVE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_ACHIVE_HEADER_XREF_T_NGS_DATA_FEATURES_HEADER1` FOREIGN KEY (`HEADER_ID`) REFERENCES `T_NGS_DATA_FEATURES_HEADER` (`HEADER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=580 DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_COM_ACCESS_HIST 구조 내보내기
DROP TABLE IF EXISTS `T_COM_ACCESS_HIST`;
CREATE TABLE IF NOT EXISTS `T_COM_ACCESS_HIST` (
  `HIST_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(45) NOT NULL COMMENT '접속 사용자 ID',
  `ACCESS_DATE` date NOT NULL COMMENT '접속 일시',
  PRIMARY KEY (`HIST_ID`),
  KEY `fk_T_COM_ACCESS_HIST_T_COM_USER1` (`USER_ID`),
  CONSTRAINT `fk_T_COM_ACCESS_HIST_T_COM_USER1` FOREIGN KEY (`USER_ID`) REFERENCES `T_COM_USER` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자 접속 이력 정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_COM_ATTACHMENT 구조 내보내기
DROP TABLE IF EXISTS `T_COM_ATTACHMENT`;
CREATE TABLE IF NOT EXISTS `T_COM_ATTACHMENT` (
  `ATTACHMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(400) NOT NULL COMMENT '첨부파일 이름',
  `TYPE` varchar(100) DEFAULT NULL COMMENT '첨부파일 형식',
  `SIZE` bigint(20) DEFAULT NULL COMMENT '첨부파일 크기',
  `REGIST_USER` varchar(45) NOT NULL COMMENT '등록 사용자 ID',
  `REGIST_DATE` datetime NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`ATTACHMENT_ID`),
  KEY `fk_T_COM_ATTACHMENT_T_COM_USER1_idx` (`REGIST_USER`),
  CONSTRAINT `fk_T_COM_ATTACHMENT_T_COM_USER1` FOREIGN KEY (`REGIST_USER`) REFERENCES `T_COM_USER` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='첨부파일 정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_COM_CODE 구조 내보내기
DROP TABLE IF EXISTS `T_COM_CODE`;
CREATE TABLE IF NOT EXISTS `T_COM_CODE` (
  `CODE` varchar(10) NOT NULL COMMENT '공통 코드',
  `CODE_GROUP` varchar(10) NOT NULL COMMENT '그룹 코드',
  `NAME` varchar(50) NOT NULL COMMENT '코드 이름',
  `USE_YN` char(1) NOT NULL COMMENT '사용 여부',
  `REGIST_DATE` datetime NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`CODE`),
  KEY `fk_T_COM_CODE_T_COM_GROUP_CODE1_idx` (`CODE_GROUP`),
  CONSTRAINT `fk_T_COM_CODE_T_COM_GROUP_CODE1` FOREIGN KEY (`CODE_GROUP`) REFERENCES `T_COM_CODE_GROUP` (`CODE_GROUP`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='공통코드 정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_COM_CODE_GROUP 구조 내보내기
DROP TABLE IF EXISTS `T_COM_CODE_GROUP`;
CREATE TABLE IF NOT EXISTS `T_COM_CODE_GROUP` (
  `CODE_GROUP` varchar(10) NOT NULL COMMENT '그룹 코드',
  `NAME` varchar(45) NOT NULL COMMENT '그룹 이름',
  `USE_YN` char(1) NOT NULL COMMENT '사용여부',
  `REGIST_DATE` datetime NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`CODE_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='공통코드 그룹 정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_COM_USER 구조 내보내기
DROP TABLE IF EXISTS `T_COM_USER`;
CREATE TABLE IF NOT EXISTS `T_COM_USER` (
  `USER_ID` varchar(45) NOT NULL COMMENT '사용자 ID',
  `PASSWORD` varchar(45) NOT NULL COMMENT '비밀번호',
  `NAME` varchar(45) NOT NULL COMMENT '사용자 이름',
  `EMAIL` varchar(100) DEFAULT NULL COMMENT '전자우편',
  `INSTITUTE` varchar(100) DEFAULT NULL COMMENT '소속 기관',
  `DEPARTMENT` varchar(100) DEFAULT NULL COMMENT '소속 부서',
  `PHONE` varchar(20) DEFAULT NULL COMMENT '연락처',
  `AUTHORITY` varchar(45) NOT NULL DEFAULT 'member' COMMENT '관리자 권한',
  `REGIST_DATE` datetime NOT NULL COMMENT '등록 일시',
  `UPDATE_USER` varchar(45) DEFAULT NULL COMMENT '변경 사용자',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '변경 일시',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자 정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_NGS_DATA_ACHIVE 구조 내보내기
DROP TABLE IF EXISTS `T_NGS_DATA_ACHIVE`;
CREATE TABLE IF NOT EXISTS `T_NGS_DATA_ACHIVE` (
  `ACHIVE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `REGIST_ID` int(11) NOT NULL COMMENT 'NGS 데이터 등록정보 ID',
  `REGIST_NO` varchar(45) NOT NULL COMMENT 'NGS 성과물 등록번호',
  `FILE_TYPE` varchar(45) NOT NULL COMMENT '파일 유형',
  `FILE_NAME` varchar(250) NOT NULL COMMENT '파일 이름',
  `FILE_SIZE` bigint(20) NOT NULL COMMENT '파일 크기',
  `FILE_CHECKSUM` varchar(45) DEFAULT NULL COMMENT 'MD5 체크섬',
  `VERIFI_STATUS` varchar(45) DEFAULT NULL COMMENT '데이터 검증 상태',
  `VERIFI_ERROR` varchar(4000) DEFAULT NULL COMMENT '데이터 검증 로그',
  `REGIST_STATUS` varchar(45) DEFAULT NULL COMMENT '등록 상태',
  `REGIST_USER` varchar(45) NOT NULL COMMENT '등록 사용자 ID',
  `REGIST_DATE` datetime NOT NULL COMMENT '등록 일시',
  `UPDATE_USER` varchar(45) NOT NULL COMMENT '변경 사용자 ID',
  `UPDATE_DATE` datetime NOT NULL COMMENT '변경 일시',
  PRIMARY KEY (`ACHIVE_ID`),
  KEY `fk_T_NGS_DATA_ACHIVE_T_COM_USER1_idx` (`REGIST_USER`),
  KEY `fk_T_NGS_DATA_ACHIVE_T_COM_USER2_idx` (`UPDATE_USER`),
  KEY `fk_T_NGS_DATA_ACHIVE_T_NGS_REGIST1_idx` (`REGIST_ID`),
  CONSTRAINT `fk_T_NGS_DATA_ACHIVE_T_COM_USER1` FOREIGN KEY (`REGIST_USER`) REFERENCES `T_COM_USER` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_NGS_DATA_ACHIVE_T_COM_USER2` FOREIGN KEY (`UPDATE_USER`) REFERENCES `T_COM_USER` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_NGS_DATA_ACHIVE_T_NGS_REGIST1` FOREIGN KEY (`REGIST_ID`) REFERENCES `T_NGS_DATA_REGIST` (`REGIST_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=127 DEFAULT CHARSET=utf8 COMMENT='NGS 성과물 파일 정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_NGS_DATA_ACHIVE_LOG 구조 내보내기
DROP TABLE IF EXISTS `T_NGS_DATA_ACHIVE_LOG`;
CREATE TABLE IF NOT EXISTS `T_NGS_DATA_ACHIVE_LOG` (
  `LOG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACHIVE_ID` int(11) NOT NULL COMMENT 'NGS 성과물 파일 ID',
  `PROCESS_TYPE` varchar(45) NOT NULL COMMENT 'NGS 성과물 처리 종류',
  `PROCESS_STATUS` varchar(45) NOT NULL COMMENT 'NGS 성과물 처리 상태',
  `PROCESS_LOG` text COMMENT 'NGS 성과물 처리 로그',
  `REGIST_USER` varchar(45) NOT NULL COMMENT '등록 사용자 ID',
  `REGIST_DATE` date NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`LOG_ID`),
  KEY `fk_T_NGS_DATA_ACHIVE_LOG_T_NGS_DATA_ACHIVE1_idx` (`ACHIVE_ID`),
  KEY `fk_T_NGS_DATA_ACHIVE_LOG_T_COM_USER1_idx` (`REGIST_USER`),
  CONSTRAINT `fk_T_NGS_DATA_ACHIVE_LOG_T_COM_USER1` FOREIGN KEY (`REGIST_USER`) REFERENCES `T_COM_USER` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_NGS_DATA_ACHIVE_LOG_T_NGS_DATA_ACHIVE1` FOREIGN KEY (`ACHIVE_ID`) REFERENCES `T_NGS_DATA_ACHIVE` (`ACHIVE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=402 DEFAULT CHARSET=utf8 COMMENT='NGS성과물 파일 처리 로그';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_NGS_DATA_FEATURES 구조 내보내기
DROP TABLE IF EXISTS `T_NGS_DATA_FEATURES`;
CREATE TABLE IF NOT EXISTS `T_NGS_DATA_FEATURES` (
  `FEATURES_ID` int(11) NOT NULL AUTO_INCREMENT,
  `HEADER_ID` int(11) NOT NULL,
  `TYPE` varchar(20) DEFAULT NULL,
  `GENE` varchar(20) DEFAULT NULL,
  `START` int(11) DEFAULT NULL,
  `END` int(11) DEFAULT NULL,
  `STRAND` varchar(10) DEFAULT NULL,
  `PRODUCT` varchar(300) DEFAULT NULL,
  `SEQUENCE` text,
  `CODON_START` int(11) DEFAULT NULL,
  `EC_NUMBER` varchar(50) DEFAULT NULL,
  `PROTEIN_ID` varchar(30) DEFAULT NULL,
  `TRANSL_TABLE` int(11) DEFAULT NULL,
  `LOCUS_TAG` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`FEATURES_ID`),
  KEY `fk_T_NGS_DATA_FEATURES_T_NGS_DATA_FEATURES_HEADER1_idx` (`HEADER_ID`),
  CONSTRAINT `fk_T_NGS_DATA_FEATURES_T_NGS_DATA_FEATURES_HEADER1` FOREIGN KEY (`HEADER_ID`) REFERENCES `T_NGS_DATA_FEATURES_HEADER` (`HEADER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=294020 DEFAULT CHARSET=utf8 COMMENT='.gbk 파일의 특성 정보들';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_NGS_DATA_FEATURES_HEADER 구조 내보내기
DROP TABLE IF EXISTS `T_NGS_DATA_FEATURES_HEADER`;
CREATE TABLE IF NOT EXISTS `T_NGS_DATA_FEATURES_HEADER` (
  `HEADER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCESSION` varchar(40) DEFAULT NULL,
  `LOCUS` varchar(40) DEFAULT NULL,
  `ORGANISM` varchar(100) DEFAULT NULL,
  `STRAIN` varchar(45) DEFAULT NULL,
  `DATE` date DEFAULT NULL,
  `START` int(11) DEFAULT NULL,
  `END` int(11) DEFAULT NULL,
  PRIMARY KEY (`HEADER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=586 DEFAULT CHARSET=utf8 COMMENT='.gbk 파일의 기본정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_NGS_DATA_FEATURES_XREF 구조 내보내기
DROP TABLE IF EXISTS `T_NGS_DATA_FEATURES_XREF`;
CREATE TABLE IF NOT EXISTS `T_NGS_DATA_FEATURES_XREF` (
  `XREF_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYPE` varchar(10) DEFAULT NULL,
  `VALUE` varchar(11) DEFAULT NULL,
  `FEATURES_ID` int(11) NOT NULL,
  PRIMARY KEY (`XREF_ID`),
  KEY `fk_T_NGS_DATA_FEATURES_XREF_T_NGS_DATA_FEATURES1_idx` (`FEATURES_ID`),
  CONSTRAINT `fk_T_NGS_DATA_FEATURES_XREF_T_NGS_DATA_FEATURES1` FOREIGN KEY (`FEATURES_ID`) REFERENCES `T_NGS_DATA_FEATURES` (`FEATURES_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=15419 DEFAULT CHARSET=utf8 COMMENT='db_xref 정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_NGS_DATA_LINK 구조 내보내기
DROP TABLE IF EXISTS `T_NGS_DATA_LINK`;
CREATE TABLE IF NOT EXISTS `T_NGS_DATA_LINK` (
  `RELATION` varchar(45) DEFAULT NULL COMMENT '연관성',
  `PROCESSED_REGIST_ID` int(11) NOT NULL COMMENT 'NGS 분석데이터 ID',
  `RAW_REGIST_ID` int(11) NOT NULL COMMENT 'NGS 원시 데이터 ID',
  PRIMARY KEY (`PROCESSED_REGIST_ID`,`RAW_REGIST_ID`),
  KEY `fk_NgsDataLink_RAW_ID_idx` (`RAW_REGIST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='원시데이터 분석데이터 연계정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_NGS_DATA_REGIST 구조 내보내기
DROP TABLE IF EXISTS `T_NGS_DATA_REGIST`;
CREATE TABLE IF NOT EXISTS `T_NGS_DATA_REGIST` (
  `REGIST_ID` int(11) NOT NULL AUTO_INCREMENT,
  `REGIST_NO` varchar(45) NOT NULL COMMENT 'NGS 데이터 등록번호',
  `TAXON_ID` int(11) NOT NULL COMMENT 'Taxonomy ID',
  `DATA_TYPE` varchar(45) NOT NULL COMMENT 'NGS 데이터 종류 (raw, processed)',
  `STRAIN` varchar(45) NOT NULL COMMENT '균주(Strain) 정보',
  `OPEN_YN` varchar(45) DEFAULT 'N' COMMENT '공개여부',
  `OPEN_DATE` date DEFAULT NULL COMMENT '공개일',
  `APPROVAL_STATUS` varchar(45) DEFAULT NULL COMMENT '승인상태 (WAIT = 제출대기, ACCEPT = 제출승인, REJECT = 제출거절)',
  `APPROVAL_USER` varchar(45) DEFAULT NULL COMMENT '승인 사용자 ID',
  `APPROVAL_DATE` date DEFAULT NULL COMMENT '승인일',
  `REGIST_STATUS` varchar(45) NOT NULL DEFAULT 'READY' COMMENT '등록상태 \n * READY = 제출 대기(작성상태), \n * VERIFYING = 파일 검증 중\n * VERIF_SUCCESS = 파일 검증 완료\n * VERIF_FAIL = 파일 검증 실패, \n * SUBMIT = 제출 진행\n * COMPLETE = 제출 완료 ',
  `REGIST_USER` varchar(45) NOT NULL COMMENT '등록 사용자 ID',
  `REGIST_DATE` datetime NOT NULL COMMENT '등록 일시',
  `UPDATE_USER` varchar(45) NOT NULL COMMENT '변경 사용자 ID',
  `UPDATE_DATE` datetime NOT NULL COMMENT '변경 일시',
  PRIMARY KEY (`REGIST_ID`),
  KEY `fk_T_NGS_REGIST_T_COM_USER1_idx` (`REGIST_USER`),
  KEY `fk_T_NGS_REGIST_T_COM_USER2_idx` (`UPDATE_USER`),
  KEY `fk_T_NGS_REGIST_T_TAXON1_idx` (`TAXON_ID`),
  CONSTRAINT `fk_T_NGS_REGIST_T_COM_USER1` FOREIGN KEY (`REGIST_USER`) REFERENCES `T_COM_USER` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_NGS_REGIST_T_COM_USER2` FOREIGN KEY (`UPDATE_USER`) REFERENCES `T_COM_USER` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_NGS_REGIST_T_TAXON1` FOREIGN KEY (`TAXON_ID`) REFERENCES `T_TAXON` (`TAXON_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=utf8 COMMENT='NGS 데이터 등록 정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_NGS_FILE_ANNOTATION 구조 내보내기
DROP TABLE IF EXISTS `T_NGS_FILE_ANNOTATION`;
CREATE TABLE IF NOT EXISTS `T_NGS_FILE_ANNOTATION` (
  `ANNOTATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACHIVE_ID` int(11) NOT NULL COMMENT 'NGS 데이터 성과물 ID',
  `GENE_COUNT` int(11) DEFAULT NULL COMMENT '유전자 개수',
  `CDS_COUNT` int(11) DEFAULT NULL COMMENT 'CDS 개수',
  `REGIST_DATE` datetime NOT NULL COMMENT '등록 일시',
  `REGIST_USER` varchar(45) NOT NULL COMMENT '등록 사용자 ID',
  PRIMARY KEY (`ANNOTATION_ID`),
  KEY ` fk_NGS파일주석정보_성과물ID_idx` (`ACHIVE_ID`),
  KEY `fk_T_NGS_FILE_ANNOTATION_T_COM_USER1_idx` (`REGIST_USER`),
  CONSTRAINT ` fk_NGS파일주석정보_성과물ID` FOREIGN KEY (`ACHIVE_ID`) REFERENCES `T_NGS_DATA_ACHIVE` (`ACHIVE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_NGS_FILE_ANNOTATION_T_COM_USER1` FOREIGN KEY (`REGIST_USER`) REFERENCES `T_COM_USER` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=563 DEFAULT CHARSET=utf8 COMMENT='NGS 데이터 성과물 주석 정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_NGS_FILE_QC_RESULT 구조 내보내기
DROP TABLE IF EXISTS `T_NGS_FILE_QC_RESULT`;
CREATE TABLE IF NOT EXISTS `T_NGS_FILE_QC_RESULT` (
  `RESULT_ID` int(11) NOT NULL DEFAULT '0',
  `ACHIVE_ID` int(11) NOT NULL COMMENT 'NGS 성과물 ID',
  `FILE_NAME` varchar(250) DEFAULT NULL COMMENT 'NGS 성과물 파일 이름',
  `FILE_PATH` varchar(1024) DEFAULT NULL COMMENT 'NGS 성과물 QC 파일 경로',
  `FILE_SIZE` bigint(20) DEFAULT NULL COMMENT 'NGS 성과물 QC 파일크기',
  `FILE_TYPE` varchar(45) DEFAULT NULL COMMENT 'NGS 성과물 QC 파일 형식',
  `QC_SUMMARY` varchar(4000) DEFAULT NULL COMMENT 'NGS 성과물 QC 결과 요약설명',
  `QC_STATUS` varchar(45) DEFAULT NULL COMMENT 'NGS 성과물 QC 결과 상태',
  `REGIST_USER` varchar(45) NOT NULL COMMENT '등록 사용자 ID',
  `REGIST_DATE` datetime NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`RESULT_ID`),
  KEY `fk_NGS파일QC_성과물ID_idx` (`ACHIVE_ID`),
  KEY `fk_T_NGS_FILE_QC_T_COM_USER1_idx` (`REGIST_USER`),
  CONSTRAINT `fk_NGS파일QC_성과물ID` FOREIGN KEY (`ACHIVE_ID`) REFERENCES `T_NGS_DATA_ACHIVE` (`ACHIVE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_NGS_FILE_QC_T_COM_USER1` FOREIGN KEY (`REGIST_USER`) REFERENCES `T_COM_USER` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='NGS 성과물 QC 정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_NGS_FILE_QC_SUMMARY 구조 내보내기
DROP TABLE IF EXISTS `T_NGS_FILE_QC_SUMMARY`;
CREATE TABLE IF NOT EXISTS `T_NGS_FILE_QC_SUMMARY` (
  `SUMMARY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACHIVE_ID` int(11) NOT NULL COMMENT 'NGS 성과물 ID',
  `SUMMARY` text COMMENT 'NGS 성과물 QC 요약설명',
  `QC_STATUS` varchar(45) NOT NULL COMMENT '요약설명',
  `REGIST_USER` varchar(45) NOT NULL COMMENT '등록 사용자 ID',
  `REGIST_DATE` datetime NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`SUMMARY_ID`),
  KEY `fk_QC_SUMMARY_ACHIVE_ID_idx` (`ACHIVE_ID`),
  CONSTRAINT `fk_QC_SUMMARY_ACHIVE_ID` FOREIGN KEY (`ACHIVE_ID`) REFERENCES `T_NGS_DATA_ACHIVE` (`ACHIVE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='NGS 성과물 QC 결과 요약설명';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_NGS_FILE_SEQ_QUANTITY 구조 내보내기
DROP TABLE IF EXISTS `T_NGS_FILE_SEQ_QUANTITY`;
CREATE TABLE IF NOT EXISTS `T_NGS_FILE_SEQ_QUANTITY` (
  `QUANTITY_ID` int(11) NOT NULL DEFAULT '0',
  `ACHIVE_ID` int(11) NOT NULL COMMENT 'NGS 성과물 ID',
  `SEQ_READ_COUNT` int(11) DEFAULT NULL COMMENT '서열 리드 개수',
  `SEQ_TOTAL_LENGTH` int(11) DEFAULT NULL COMMENT '서열 전체 길이',
  `SEQ_AVERAGE_LENGTH` int(11) DEFAULT NULL COMMENT '서열 평균 길이',
  `A_SEQ_COUNT` int(11) DEFAULT NULL COMMENT '염기서열 A 개수',
  `T_SEQ_COUNT` int(11) DEFAULT NULL COMMENT '염기서열 T 개수',
  `G_SEQ_COUNT` int(11) DEFAULT NULL COMMENT '염기서열 G 개수',
  `C_SEQ_COUNT` int(11) DEFAULT NULL COMMENT '염기서열 C 개수',
  `N_SEQ_COUNT` int(11) DEFAULT NULL COMMENT '염기서열 N 개수',
  `N50_LENGTH` int(11) DEFAULT NULL COMMENT 'N50길이',
  `REGIST_USER` varchar(45) NOT NULL COMMENT '등록 사용자 ID',
  `REGIST_DATE` datetime NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`QUANTITY_ID`),
  KEY `fk_NGS파일_정량정보_성과물ID_idx` (`ACHIVE_ID`),
  KEY `fk_T_NGS_FILE_DOSE_T_COM_USER1_idx` (`REGIST_USER`),
  CONSTRAINT `fk_NGS파일_정량정보_성과물ID` FOREIGN KEY (`ACHIVE_ID`) REFERENCES `T_NGS_DATA_ACHIVE` (`ACHIVE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_NGS_FILE_DOSE_T_COM_USER1` FOREIGN KEY (`REGIST_USER`) REFERENCES `T_COM_USER` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='NGS 성과물 정량정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_NGS_PROCESSED_DATA 구조 내보내기
DROP TABLE IF EXISTS `T_NGS_PROCESSED_DATA`;
CREATE TABLE IF NOT EXISTS `T_NGS_PROCESSED_DATA` (
  `REGIST_ID` int(11) NOT NULL COMMENT 'NGS 데이터 등록정보 ID',
  `SUBMITTER` varchar(50) NOT NULL COMMENT 'NGS 데이터 제출자',
  `SUBMIT_ORGAN` varchar(100) NOT NULL COMMENT 'NGS 데이터 제출 기관',
  `PROJECT` varchar(100) NOT NULL COMMENT 'NGS 데이터 분석 프로젝트',
  `PROJECT_TYPE` varchar(100) NOT NULL COMMENT 'NGS 데이터 분석 프로젝트 유형',
  `SUBMIT_COMMENT` text COMMENT 'NGS 데이터 제출 요약설명',
  `ASSEMBLY_METHOD` varchar(100) DEFAULT NULL COMMENT 'NGS 시퀀싱 조립 방법',
  `ASSEMBLY_LEVEL_CD` varchar(10) NOT NULL COMMENT 'NGS 시퀀싱 조립 수준 코드',
  `GENOME_TYPE_CD` varchar(10) NOT NULL COMMENT '유전체 종류',
  `GENOME_COVERAGE` varchar(45) DEFAULT NULL COMMENT '유전체 범위',
  `SEQ_COMMENT` text COMMENT 'NGS 시퀀싱 요약설명',
  `REF_TITLE` varchar(100) DEFAULT NULL COMMENT '참조문헌 제목',
  `REF_PUB_STATUS` varchar(45) DEFAULT NULL COMMENT '참조문헌 출판 상태',
  `REF_COMMENT` text COMMENT '참조문헌 요약설명',
  PRIMARY KEY (`REGIST_ID`),
  KEY `fk_T_NGS_ANNOTATION_DATA_T_COM_CODE1_idx` (`GENOME_TYPE_CD`),
  KEY `fk_T_NGS_ANNOTATION_DATA_T_COM_CODE2_idx` (`ASSEMBLY_LEVEL_CD`),
  KEY `fk_T_NGS_ANNOTATION_DATA_T_NGS_REGIST1_idx` (`REGIST_ID`),
  CONSTRAINT `fk_T_NGS_ANNOTATION_DATA_T_COM_CODE1` FOREIGN KEY (`GENOME_TYPE_CD`) REFERENCES `T_COM_CODE` (`CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_NGS_ANNOTATION_DATA_T_COM_CODE2` FOREIGN KEY (`ASSEMBLY_LEVEL_CD`) REFERENCES `T_COM_CODE` (`CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_NGS_ANNOTATION_DATA_T_NGS_REGIST1` FOREIGN KEY (`REGIST_ID`) REFERENCES `T_NGS_DATA_REGIST` (`REGIST_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='NGS 분석 정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_NGS_RAW_DATA 구조 내보내기
DROP TABLE IF EXISTS `T_NGS_RAW_DATA`;
CREATE TABLE IF NOT EXISTS `T_NGS_RAW_DATA` (
  `REGIST_ID` int(11) NOT NULL COMMENT 'NGS 데이터 등록정보 ID',
  `EXPR_TYPE_CD` varchar(10) NOT NULL COMMENT '실험유형 코드',
  `DOMAIN_CD` varchar(10) NOT NULL COMMENT '미생물 분류 코드',
  `CULTURE_CONDITION` varchar(4000) DEFAULT NULL COMMENT '시료 배양조건',
  `TREATMENT` varchar(4000) DEFAULT NULL COMMENT '시료 처리',
  `REPLICATE_CD` varchar(10) NOT NULL COMMENT '반복실험 유형 코드',
  `SAMPLE_NAME` varchar(100) NOT NULL COMMENT '시료 이름',
  `ORGANISM_TYPE` varchar(100) NOT NULL COMMENT '시료 개체 유형',
  `SAMPLE_TYPE` varchar(45) NOT NULL COMMENT '시료 유형',
  `SAMPLE_SOURCE_CD` varchar(10) NOT NULL COMMENT '시료 추출 소스',
  `GEOGRAPH_LOCATION` varchar(250) NOT NULL COMMENT '시료 채집 지역',
  `SAMPLE_COMMENT` text COMMENT '샘플 요약설명',
  `PLATFORM_CD` varchar(10) NOT NULL COMMENT 'NGS 시퀀싱 플랫폼 코드',
  `CONSTRUCTION` varchar(100) NOT NULL COMMENT 'NGS 시퀀싱 라이브러리 구축방법',
  `SELECTION` varchar(100) NOT NULL COMMENT 'NGS 시퀀싱 선택 방법',
  `SEQUENCER` varchar(250) NOT NULL COMMENT 'NGS 시퀀싱 장비(모델)',
  `STRATEGY` varchar(100) NOT NULL COMMENT '시퀀싱 전략',
  `READ_LENGTH` int(11) DEFAULT NULL COMMENT '서열 리드 길이',
  `INSERT_SIZE` int(11) DEFAULT NULL COMMENT '서열 삽입 크기',
  `READ_TYPE_CD` varchar(10) NOT NULL COMMENT ' 리드 유형 코드(single-end, paired-end)',
  `ADAPTER_SEQ` varchar(250) DEFAULT NULL COMMENT 'NGS 시퀀싱 어댑터 서열',
  `QUALITY_SCORE_VERSION` varchar(100) DEFAULT NULL COMMENT 'quality score version',
  `BASE_CALLING_PROGRAM` varchar(100) DEFAULT NULL COMMENT 'base calling program',
  `LIBRARY_COMMENT` text COMMENT 'Library 요약설명',
  PRIMARY KEY (`REGIST_ID`),
  KEY `fk_RAW_DATA_T_COM_CODE1_idx` (`EXPR_TYPE_CD`),
  KEY `fk_RAW_DATA_T_COM_CODE2_idx` (`DOMAIN_CD`),
  KEY `fk_RAW_DATA_T_COM_CODE3_idx` (`REPLICATE_CD`),
  KEY `fk_RAW_DATA_T_COM_CODE4_idx` (`SAMPLE_SOURCE_CD`),
  KEY `fk_RAW_DATA_T_COM_CODE5_idx` (`PLATFORM_CD`),
  KEY `fk_T_NGS_RAW_DATA_T_COM_CODE1_idx` (`READ_TYPE_CD`),
  KEY `fk_T_NGS_RAW_DATA_T_NGS_REGIST1_idx` (`REGIST_ID`),
  CONSTRAINT `fk_RAW_DATA_T_COM_CODE1` FOREIGN KEY (`EXPR_TYPE_CD`) REFERENCES `T_COM_CODE` (`CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_RAW_DATA_T_COM_CODE2` FOREIGN KEY (`DOMAIN_CD`) REFERENCES `T_COM_CODE` (`CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_RAW_DATA_T_COM_CODE3` FOREIGN KEY (`REPLICATE_CD`) REFERENCES `T_COM_CODE` (`CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_RAW_DATA_T_COM_CODE4` FOREIGN KEY (`SAMPLE_SOURCE_CD`) REFERENCES `T_COM_CODE` (`CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_RAW_DATA_T_COM_CODE5` FOREIGN KEY (`PLATFORM_CD`) REFERENCES `T_COM_CODE` (`CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_NGS_RAW_DATA_T_COM_CODE1` FOREIGN KEY (`READ_TYPE_CD`) REFERENCES `T_COM_CODE` (`CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_NGS_RAW_DATA_T_NGS_REGIST1` FOREIGN KEY (`REGIST_ID`) REFERENCES `T_NGS_DATA_REGIST` (`REGIST_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='NGS 원시 데이터 정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_RESEARCH_ATTACHMENT 구조 내보내기
DROP TABLE IF EXISTS `T_RESEARCH_ATTACHMENT`;
CREATE TABLE IF NOT EXISTS `T_RESEARCH_ATTACHMENT` (
  `ATTACHMENT_ID` int(11) NOT NULL COMMENT '첨부파일 식별번호',
  `RESEARCH_ID` int(11) NOT NULL COMMENT '성과물 ID',
  `REGIST_NO` varchar(45) NOT NULL COMMENT '첨부파일 등록번호',
  `FILE_NAME` varchar(250) NOT NULL COMMENT '첩부파일 이름',
  `FILE_SIZE` bigint(20) NOT NULL DEFAULT '0' COMMENT '첨부파일 크기',
  `FILE_TYPE` varchar(45) NOT NULL COMMENT '첨부파일 용량',
  `DESCRIPTION` text COMMENT '첨부파일 설명(캡션)',
  `REGIST_USER` varchar(45) NOT NULL COMMENT '등록 사용자 ID',
  `REGIST_DATE` datetime NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`ATTACHMENT_ID`),
  KEY `fk_T_RESEARCH_ATTACHMENT_RESEARCH_ID_idx` (`RESEARCH_ID`),
  CONSTRAINT `fk_RESEARCH_ATTACHMENT_RESEARCH_ID` FOREIGN KEY (`RESEARCH_ID`) REFERENCES `T_RESEARCH_DATA` (`RESEARCH_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='성과물 첨부파일 정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_RESEARCH_DATA 구조 내보내기
DROP TABLE IF EXISTS `T_RESEARCH_DATA`;
CREATE TABLE IF NOT EXISTS `T_RESEARCH_DATA` (
  `RESEARCH_ID` int(11) NOT NULL COMMENT '성과물 식별번호',
  `REGIST_NO` varchar(45) NOT NULL COMMENT '성과물 등록번호',
  `TITLE` varchar(3000) NOT NULL COMMENT '성과물 제목',
  `JOURNAL` varchar(500) DEFAULT NULL,
  `VOLUME` varchar(45) DEFAULT NULL,
  `ISSUE` varchar(45) DEFAULT NULL,
  `PAGES` varchar(45) DEFAULT NULL,
  `PUBLISHED` varchar(45) DEFAULT NULL,
  `SUBMITTER` varchar(1000) NOT NULL COMMENT '제출자',
  `SUBMIT_ORGAN` varchar(1000) NOT NULL COMMENT '제출 기관',
  `FULL_TEXT_LINK` varchar(1000) NOT NULL COMMENT '원본 사이트 주소',
  `CONTENT` text COMMENT '성과물 내용(초록)',
  `OPEN_YN` varchar(45) DEFAULT 'N' COMMENT '공개여부',
  `OPEN_DATE` date DEFAULT NULL COMMENT '공개일',
  `REGIST_STATUS` varchar(45) NOT NULL COMMENT '등록상태( READY=작성중,  VERIFYING=검증중,  VERIF_SUCCESS =검증성공, VERIF_FAIL=검증실패, COMPLETE=제출완료)',
  `REGIST_USER` varchar(45) NOT NULL COMMENT '등록 사용자 ID',
  `REGIST_DATE` datetime NOT NULL COMMENT '등록 일시',
  `UPDATE_USER` varchar(45) DEFAULT NULL COMMENT '변경 사용자 ID',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '변경 일시',
  PRIMARY KEY (`RESEARCH_ID`),
  UNIQUE KEY `REGIST_NO_UNIQUE` (`REGIST_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='성과물(논문) 데이터';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_RESEARCH_NGS_DATA_REGIST 구조 내보내기
DROP TABLE IF EXISTS `T_RESEARCH_NGS_DATA_REGIST`;
CREATE TABLE IF NOT EXISTS `T_RESEARCH_NGS_DATA_REGIST` (
  `RESEARCH_ID` int(11) NOT NULL COMMENT '성과물 ID',
  `REGIST_ID` int(11) NOT NULL COMMENT 'NGS 데이터 등록 ID',
  PRIMARY KEY (`RESEARCH_ID`,`REGIST_ID`),
  KEY `fk_RESEARCH_NGS_REGIST_ID` (`REGIST_ID`),
  CONSTRAINT `fk_RESEARCH_NGS_REGIST_ID` FOREIGN KEY (`REGIST_ID`) REFERENCES `T_NGS_DATA_REGIST` (`REGIST_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESEARCH_NGS_RESEARCH_ID` FOREIGN KEY (`RESEARCH_ID`) REFERENCES `T_RESEARCH_DATA` (`RESEARCH_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='성과물 NGS등록 데이터 연계정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_RESEARCH_OMICS_FILE 구조 내보내기
DROP TABLE IF EXISTS `T_RESEARCH_OMICS_FILE`;
CREATE TABLE IF NOT EXISTS `T_RESEARCH_OMICS_FILE` (
  `OMICS_FILE_ID` int(11) NOT NULL COMMENT '오믹스 파일 식별번호',
  `RESEARCH_ID` int(11) NOT NULL COMMENT '성과물 ID',
  `REGIST_NO` varchar(45) NOT NULL COMMENT '오믹스 등록번호',
  `CATEGORY` varchar(45) NOT NULL COMMENT '오믹스 유형 코드',
  `FILE_NAME` varchar(250) NOT NULL COMMENT '오믹스 파일 이름',
  `FILE_SIZE` bigint(20) NOT NULL DEFAULT '0' COMMENT '오믹스 파일 용량',
  `FILE_TYPE` varchar(45) DEFAULT NULL COMMENT '오믹스 파일 종류',
  `DESCRIPTION` text COMMENT '오믹스 파일 설명',
  `REGIST_USER` varchar(45) NOT NULL COMMENT '등록 사용자 ID',
  `REGIST_DATE` datetime NOT NULL COMMENT '등록 일시',
  PRIMARY KEY (`OMICS_FILE_ID`),
  KEY `fk_RESEARCH_OMICS_RESEARCH_ID_idx` (`RESEARCH_ID`),
  CONSTRAINT `fk_RESEARCH_OMICS_RESEARCH_ID` FOREIGN KEY (`RESEARCH_ID`) REFERENCES `T_RESEARCH_DATA` (`RESEARCH_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='성과물 오믹스 파일정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_TAXON 구조 내보내기
DROP TABLE IF EXISTS `T_TAXON`;
CREATE TABLE IF NOT EXISTS `T_TAXON` (
  `TAXON_ID` int(11) NOT NULL,
  `NCBI_TAXON_ID` int(11) DEFAULT NULL,
  `PARENT_TAXON_ID` int(11) DEFAULT NULL,
  `NODE_RANK` varchar(32) DEFAULT NULL,
  `GENETIC_CODE` tinyint(4) DEFAULT NULL,
  `MITO_GENETIC_CODE` tinyint(4) DEFAULT NULL,
  `LEFT_VALUE` int(11) DEFAULT NULL,
  `RIGHT_VALUE` int(11) DEFAULT NULL,
  PRIMARY KEY (`TAXON_ID`),
  KEY `idx_T_TAXON_PARENT_TAXON_ID` (`PARENT_TAXON_ID`),
  KEY `idx_T_TAXON_NCBI_TAXON_ID` (`NCBI_TAXON_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 gdkm.T_TAXON_NAME 구조 내보내기
DROP TABLE IF EXISTS `T_TAXON_NAME`;
CREATE TABLE IF NOT EXISTS `T_TAXON_NAME` (
  `TAXON_ID` int(11) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `NAME_CLASS` varchar(32) DEFAULT NULL,
  KEY `T_TAXON_T_TAXON_NAME_FK` (`TAXON_ID`),
  KEY `T_TAXON_NAME_IDX` (`NAME`),
  KEY `idx_T_TAXON_NAME_NAME_CLASS` (`NAME_CLASS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
